apiVersion: v1
kind: Service
metadata:
  name: flask-app-depl
  labels:
    type: observability
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: flask-app-ui
  selector:
    type: observability    