apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  selector:
    app: otel-collector  # Matches the labels in your Deployment
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: metrics
      port: 9464
      targetPort: 9464