apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: otel-collector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 8s
  namespaceSelector:
    matchNames:
      - default
